### ISSUE TITLE
JSONException: End of input at character 0 of

### ISSUE THREAD

**Issue by sebastian-palma** [mobilesiri/JSON-Parsing-in-Android#1]
Without touching the code, cloning the repository and testing in a Moto G 3rd generation, it doesn't work: the exception is: org.json.JSONException: End of input at character 0 of.

**Comment by jdiamand** [comment]
comment out setDoOutput as follows:
//conn.setDoOutput(true);

**Comment by sebastian-palma** [comment]
Thanks @jdiamand, let me try and I'll comment you.

**Comment by koossaayy** [comment]
@jdiamand Thank You :dancer:

**Comment by mobilesiri** [comment]
Thanks @jdiamand
Fixed in 26f11e8c880a50b48e9e61237ff4525db9e8a377
